import AppLayout from '@/layouts/AppLayout'
import NextIntlClientProvider from '@/providers/NextIntlClientProvider'
import { Metadata } from 'next'
import '../globals.css'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

const RootLayout = async ({
	children,
	params,
}: {
	children: React.ReactNode
	params: { locale: string }
}) => {
	const { locale } = await params
	return (
		<html lang={locale}>
			<body>
				<NextIntlClientProvider locale={locale}>
					<AppLayout>{children}</AppLayout>
				</NextIntlClientProvider>
			</body>
		</html>
	)
}
export default RootLayout
