import AppLayout from '@/layouts/AppLayout'
import NextIntlClientProvider from '@/providers/NextIntlClientProvider'
import { Metadata } from 'next'
import '../globals.css'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default async function RootLayout({
	children,
	params,
}: {
	children: React.ReactNode
	params: { locale: string }
}) {
	const { locale } = await params
	return (
		<NextIntlClientProvider locale={locale}>
			<html lang={locale}>
				<body>
					<AppLayout>{children}</AppLayout>
				</body>
			</html>
		</NextIntlClientProvider>
	)
}
